# Generated by Django 4.1.2 on 2022-10-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_tracker', '0002_auto_20210809_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('price_difference', '-created')},
        ),
    ]
